[package]
name = "aya"
version = "0.0.1"
authors = ["Aya Project"]
license = "Apache-2.0"

[addresses]
aya = "0x8e9187b49143e6071d8bdee63e34224a8e79fdaa6207d2d2ed54007c45936e0b"
default = "0x2"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", rev = "main" }
