[package]
name = "aya"
version = "0.1.0"
authors = ["Aya Developers Team"]

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move", subdir = "language/move-stdlib", rev = "current_release" }
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "sui-move", rev = "current_release" }

[addresses]
Std = "0x1"
Sui = "0x2"
aya = "0x8e9187b49143e6071d8bdee63e34224a8e79fdaa6207d2d2ed54007c45936e0b"

[build]
sources = ["sources"]
bytecode_version = 6
