services:
  - type: web
    name: aya-game
    env: node
    buildCommand: npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://www.ayaonsui.xyz
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "*"
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Cross-Origin-Resource-Policy
        value: cross-origin
    autoDeploy: true
