services:
  - type: web
    name: aya-game
    env: node
    buildCommand: npm run render-build
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 10000
    autoDeploy: true
